site:
  title: {{cookiecutter.project_title}}
  url: {{cookiecutter.project_url}}
  start_page: {{cookiecutter.antora_prefix}}::index.adoc
  keys:
    google_analytics: ''
content:
  sources:
  - url: .                 # The current folder is a git repo
    branches: HEAD         # "HEAD" uses whichever branch is currently checked out
    start_path: docs
    edit_url: 'https://git.vshn.net/vshn/{{cookiecutter.project_slug}}/edit/develop/{path}'
ui:
  bundle:
{% if cookiecutter.antora_theme == "vshn" %}
    url: https://github.com/vshn/antora-ui-default/releases/download/2.0.1/ui-bundle.zip
{% elif cookiecutter.antora_theme == "appuio" %}
    url: https://github.com/appuio/antora-ui-default/releases/download/1.0/ui-bundle.zip
{% elif cookiecutter.antora_theme == "syn" %}
    url: https://github.com/projectsyn/antora-ui-default/releases/download/1.4/ui-bundle.zip
{% endif %}
    snapshot: false
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
    kroki-fetch-diagram: ''
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true

