= {{cookiecutter.project_title}}

This is an https://antora.org/[Antora] documentation website, available at {{cookiecutter.project_url}}.

== Basic Antora Setup

* The documentation pages are stored in the `docs/modules/ROOT/pages` folder.
* Images are stored in the `docs/modules/ROOT/assets/images` folder.
* E-book specific files are located in the `docs/ebook` folder, including the https://www.gimp.org/[Gimp] template of the cover.

== Different Kinds of Antora Websites

There are two possible Antora projects:

* Those including both a `playbook.yml` and `docs/antora.yml` files; and
* Those only including one of them and not the other.

The file `docs/antora.yml` defines a documentation component including several modules. It specifies the name and entry point of a component.

On the other hand, the file `playbook.yml` is used to coalesce various documentation components into one website. It specifies the build order and the style to apply to the final website.

If your project only requires to be documented, but does _not_ take the responsibility for the build process of the documentation, you can remove the `.gitlab-ci.yml`, `Makefile`, and `playbook.yml` files.

On the other hand, projects in charge of documentation building do not always include documentation themselves; in those cases the `docs` folder can be safely deleted, only leaving the `playbook.yml` file.

== Usage

. `make preview` to launch a "live preview" version of the documentation.
. `make html` to create the Antora website in the `_public` subfolder.
. `make pdf epub kindle manpage` to create the corresponding e-books in the `_public` subfolder.
. `make clean` to remove all build products.

== Docker

You can create a Docker image out of this project:

[source,bash]
----
$ docker build -t {{ cookiecutter.project_slug }} -f deployment/main/Dockerfile .
$ docker run --rm --detach --publish 8080:8080 {{ cookiecutter.project_slug }}
----

The project includes sample YAML files for a suitable Kubernetes deployment.

== GitLab

This project includes a ready-to-use `.gitlab-ci.yml` file for GitLab integration.

== OpenShift GitLab CI Pipeline Setup

. Create project in https://control.vshn.net/appuio/projects
. Create credentials
+
----
oc create sa gitlab-ci
oc adm policy add-role-to-user edit -z gitlab-ci
oc sa get-token gitlab-ci
----
. Configure the token as CI/CD variable `APPUIO_REGISTRY_TOKEN` in GitLab: Settings -> CI/CD -> Variables
. Add Kubernetes Cluster under Operations -> Kubernetes (See existing docs projects for details)
. Check that the files in `deployment/` are what you actually want

