= Cookiecutter Template for Antora Documentation Sites

This project provides a https://cookiecutter.readthedocs.io/[Cookiecutter] template for creating https://antora.org/[Antora] documentation websites.

== Usage

. `cookiecutter git@git.vshn.net:vshn/antora-bootstrap`
. Follow the prompts asking for information
. `cd` into the newly created folder
. `make html` to create the Antora website in the `_public` subfolder
. `make pdf epub manpage kindle` to create the corresponding e-books

== Requirements

The requirements for this project are:

* Python 3.x
* https://cookiecutter.readthedocs.io/[Cookiecutter] 1.7 or higher.

== OpenShift GitLab CI Pipeline Setup

. Create project in https://control.vshn.net/appuio/projects
. Create credentials
+
----
oc create sa gitlab-ci
oc adm policy add-role-to-user edit -z gitlab-ci
oc sa get-token gitlab-ci
----
. Configure the token as CI/CD variable `APPUIO_REGISTRY_TOKEN` in GitLab: Settings -> CI/CD -> Variables
. Add Kubernetes Cluster under Operations -> Kubernetes (See existing docs projects for details)
. Check that the files in `deployment/` are what you actually want
