apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vshn-{{cookiecutter.project_slug}}
  labels:
    app: vshn-{{cookiecutter.project_slug}}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: {{cookiecutter.project_slug}}.appuioapp.ch
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vshn-{{cookiecutter.project_slug}}
